### ISSUE TITLE
Color scheme does not adjust for light terminal colors

### ISSUE THREAD

**Issue by gerbillinae** [jorgerojas26/lazysql#181]
The color scheme does not adjust for light terminal colors.

E.g:
![Image](https://github.com/user-attachments/assets/6685ba52-545e-4c32-ad4d-17c267e0f075)

Using iTerm2 3.5.10 on mac os 14.4.1

**Comment by anandghegde** [comment]
I'd like to work on this. Here's a proposal, and I'm happy to follow a different spec if you already have one in mind.

At the moment, most colors come from `Styles` in `app/app.go`, but about 60 `tcell.Color*` literals are spread across components. Most of them are in `sql_lexer.go`, `sql_editor.go` (status bar, autocomplete, selection) and `connection_form.go`. On a light background, the hard-coded white and dark slate gray are what break.

Proposed config:

```toml
[theme]
Preset = "light"            # "default" (today's colors) or "light"

[theme.Colors]              # optional overrides on top of the preset
Border = "#666A7E"
Title = "black"
PrimaryText = "default"
Selection = "dodgerblue"
EditorStatusBarBackground = "lightgray"
SQLKeyword = "#005F87"
```

- Values are anything `tcell.GetColor` accepts: color names, hex, or `default` for the terminal color.
- All hard-coded colors move into the `Theme` struct, so every component reads from `app.Styles`.
- The theme is applied after the config loads, since `Styles` is currently set in `init()`. It deep-merges from a local config the same way `[application]` does.
- Out of scope: detecting the terminal background automatically, and reloading the theme while the app is running.

Questions:

1. Are PascalCase keys under `[theme]` fine, or would you like the colors nested per component (`[theme.Editor]`, `[theme.Table]`)?
2. Should the first PR ship only "default" and "light", or a few more presets as well?

If this looks right, I'll open a PR.
